[package]
name = "rom_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
slint = "1.9.2"

[build-dependencies]
slint-build = "1.9.2"
