import { LineEdit, Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 800px;
    height: 400px;
    in-out property <string> chip_path;
    in-out property <string> text_path;

    // Callback to communicate with Rust
    callback request_process(string, string);

    Text {
        text: "ROM IMPORT TOOL";
        horizontal-alignment: right;
        x: 275px;
        y: 20px;
        font-size: 30px;
    }

    LineEdit {
        placeholder-text: "Path to Chip JSON";
        x: 200px;
        y: 100px;
        width: 400px;
        height: 60px;
        horizontal-alignment: center;
        text <=> root.chip_path; // Two-way binding
    }

    LineEdit {
        placeholder-text: "Path to TEXT FILE";
        x: 200px;
        y: 170px;
        width: 400px;
        height: 60px;
        horizontal-alignment: center;
        text <=> root.text_path; // Two-way binding
    }

    Rectangle {
        background: teal;
        x: 250px;
        y: 240px;
        width: 300px;
        height: 50px;
        border-radius: 6px;
        Button {
            text: "GO";
            x: 0px;
            y: 0px;
            width: 300px;
            height: 50px;
            clicked => {
                // Trigger callback with both paths
                root.request_process(root.chip_path, root.text_path);
            }
        }
    }
}